title: Sara Butler
description: Sara's personal website
author: "Sara Butler"

theme: minima

base_url: /
repository: boozey-psi/boozey-psi.github.io

# Minima social links
github_username: boozey-psi
linkedin_username: saraabutler

# Minima: show excerpts in the frontpage
show_excerpts: true

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%d-%m-%Y"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
