theme: minima
title: Sara Butler
author: Sara Butler

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%d-%m-%Y"

# Minima social links
github_username: boozey-psi
linkedin_username: saraabutler

# Minima: show excerpts in the frontpage
show_excerpts: true

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - LICENSE
    - README.md
