theme: coffeescript
title: Sara Butler
author: Sara Butler

header_pages:
  - cv.md

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
